[electron]
version = "40.8.2"
flags = [
    "--enable-features=AllowQt,GlobalShortcutsPortal,WaylandWindowDecorations",
    "--enable-wayland-ime",
    "--ozone-platform=wayland",
    "--wayland-text-input-version=3",
]
